name: increment_counter_package
description: A package with increment_counter feature.
version: 0.0.1
author: null
homepage: null

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.17.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  common_package:
    path: ../common

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
