name: Flutter - Analyze the code and Run tests (CI)

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Checkout
        uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - name: Enable Flutter web
        run: flutter config --enable-web
        working-directory: ./
      - name: Get all packages to install dependencies
        run: bash ./flutter_packages.sh
      - name: Analyze the code
        run: flutter analyze || exit 1
      - name: Run all tests
        run: bash ./tests_packages.sh
        working-directory: ./
