name: Flutter - Build and Deploy on GitHub Pages (CD)

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Checkout
        uses: actions/checkout@v2
      - name: Setup Flutter to Channel dev
        uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - name: Enable Flutter web
        run: flutter config --enable-web
        working-directory: ./
      - name: Get all packages to install dependencies
        run: bash ./flutter_packages.sh
      - name: Analyze the code
        run: flutter analyze || exit 1
      - name: Run all tests
        run: bash ./tests_packages.sh
        working-directory: ./
      - name: Build Flutter web app from a specific directory (packages/mobx_examples)
        run: |
          flutter build web --release --dart-define=FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_TEXT=true
        working-directory: ./packages/mobx_examples
      - name: Deploy Flutter web app
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packages/mobx_examples/build/web
          allow_empty_commit: true
